name: Release

on:
  release:
    types: [ released ]

jobs:
  release:
    name: Release new plugin version
    runs-on: ubuntu-latest
    env:
      PLUGIN: test
      REGISTRY_URL: ghcr.io
      REGISTRY_ORG: marinco

    steps:
      - uses: actions/checkout@v3
      - name: Set release version to environment
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Write environment values to project.properties
        run: |
          sed -i "/PLUGIN=/ s/=.*/=${{ env.PLUGIN }}/" project.properties
          sed -i "/VERSION=/ s/=.*/=${{ env.VERSION }}/" project.properties
          sed -i "/REGISTRY_URL=/ s/=.*/=${{ env.REGISTRY_URL }}/" project.properties
          sed -i "/REGISTRY_ORG=/ s/=.*/=${{ env.REGISTRY_ORG }}/" project.properties

      - name: Build jar file
        run: sh build.sh

      - name: Publish to Nexus
        run: |
          curl --fail-with-body -v -u ${{ secrets.NEXUS_CI_USER }}:${{ secrets.NEXUS_CI_USER_PWD }} \
          --upload-file build/${{ env.PLUGIN }}-${{ env.VERSION }}.jar \
          https://nexus.xebialabs.com/nexus/content/repositories/community/com/xebialabs/test/${{ env.PLUGIN }}-${{ env.VERSION }}.jar

      - name: Log in to Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.XEBIALABS_CI_USER_REPO }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: GITHUB_PAT=${{ secrets.XEBIALABS_CI_USER_REPO }}
          tags: ${{ format('{0}/{1}/{2}:{3}', env.REGISTRY_URL, env.REGISTRY_ORG, env.PLUGIN, env.VERSION) }}
